[package]
name = "bezier_converter"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.30.9"

[dev-dependencies]
anyhow = "1.0.100"
image = "0.25.9"
